export default function TermsAndConditions() {
    return (
        <div className="max-w-5xl mx-auto px-6 py-12 text-gray-800">
            <h1 className="text-3xl font-bold text-blue-600 mb-6">
                CPA Workshop – Terms of Service
            </h1>
            <p className="text-lg mb-10">
                These Terms of Service govern your use of CPA Workshop programs
                and resources, including webinars, self-study courses, and
                subscription services. By enrolling in any program, you agree to
                these terms and conditions.
            </p>

            <ol className="space-y-10 list-decimal list-inside">
                {/* 1 */}
                <li>
                    <span className="text-xl font-semibold text-blue-500 mb-2">
                        Record Retention Policy
                    </span>
                    <p>
                        In alignment with NASBA Standard No. 24, CPA Workshop
                        maintains complete records for each Group Internet-Based
                        program for a minimum of five (5) years. These records
                        include:
                    </p>
                    <ul className="list-disc pl-6 mt-2 space-y-1">
                        <li>
                            <strong>Participation records:</strong>
                            <ul className="list-disc pl-6 mt-1">
                                <li>
                                    <strong>Group Internet-Based:</strong>{" "}
                                    Attendance reports and polling data
                                    generated by our webinar platform.
                                </li>
                                <li>
                                    Group Live events are not currently offered.
                                </li>
                            </ul>
                        </li>
                        <li>
                            <strong>Program schedules:</strong> Dates and
                            delivery formats of each session.
                        </li>
                        <li>
                            <strong>
                                Instructor and reviewer credentials:
                            </strong>
                            Including full names, CPA license numbers, licensure
                            states, and status—all securely stored and made
                            available when required.
                        </li>
                        <li>
                            <strong>CPE credits issued:</strong> Documented per
                            participant.
                        </li>
                        <li>
                            <strong>Evaluation results:</strong> Feedback and
                            assessment outcomes from attendees.
                        </li>
                        <li>
                            <strong>Course materials:</strong> Including
                            announcements, agendas, speaker notes, and handouts.
                        </li>
                    </ul>
                </li>

                {/* 2 */}
                <li>
                    <span className="text-xl font-semibold text-blue-500 mb-2">
                        Refund Policy
                    </span>
                    <p>
                        The refund policy varies by program type and is
                        communicated during the registration process. In
                        general:
                    </p>
                    <ul className="list-disc pl-6 mt-2 space-y-1">
                        <li>
                            <strong>Custom Group Internet-Based Events:</strong>
                            <ul className="list-disc pl-6 mt-1">
                                <li>
                                    Written cancellation required at least
                                    <strong> one business day </strong>in
                                    advance to avoid speaker fees.
                                </li>
                                <li>
                                    Cancellations made
                                    <strong> within 2 business days</strong> of
                                    the event are
                                    <strong> non-refundable.</strong>
                                </li>
                                <li>
                                    o If unforeseen circumstances arise, CPA
                                    Workshop will make reasonable efforts to
                                    reschedule the session.
                                </li>
                            </ul>
                        </li>
                        <li>
                            <strong>
                                Live Webinars (Group Internet-Based):
                            </strong>
                            <ul className="list-disc pl-6 mt-1">
                                <li>
                                    <strong>All sales are final</strong> unless
                                    otherwise noted in the promotional material.
                                </li>
                                <li>
                                    Refunds will <strong>not be issued </strong>
                                    for no-shows or if required attendance
                                    checks are not completed.
                                </li>
                                <li>
                                    However, unused credits from cancelled
                                    registrations can be applied to a future CPA
                                    Workshop event.
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <p className="mt-2">
                        For refund or cancellation inquiries, contact us at:
                        <a
                            href="mailto:support@cpaworkshop.com"
                            className="ml-1 text-blue-600 underline"
                        >
                            support@cpaworkshop.com
                        </a>
                    </p>
                </li>

                {/* 3 */}
                <li>
                    <span className="text-xl font-semibold text-blue-500 mb-2">
                        Program Cancellation Policy
                    </span>
                    <p>
                        If CPA Workshop must cancel or reschedule a program due
                        to unforeseen circumstances, we will notify registered
                        participants immediately via email. Participants will be
                        offered:
                    </p>
                    <ul className="list-disc pl-6 mt-2 space-y-1">
                        <li>
                            A <strong> full refund,</strong> or
                        </li>
                        <li>
                            An option to <strong>reschedule</strong> or transfer
                            registration to another course.
                        </li>
                    </ul>
                </li>

                {/* 4 */}
                <li>
                    <span className="text-xl font-semibold text-blue-500 mb-2">
                        Complaint Resolution Policy
                    </span>
                    <p>
                        At CPA Workshop, we are committed to delivering
                        high-quality continuing education. If you are not fully
                        satisfied with any aspect of your course and wish to
                        file a complaint, please reach out directly to:
                    </p>
                    <p className="ml-4 mt-2">
                        <strong>Bill Murry</strong> <br />
                        📧{" "}
                        <a
                            href="mailto:bill@cpaworkshop.com"
                            className="text-blue-600 underline"
                        >
                            bill@cpaworkshop.com
                        </a>
                    </p>
                    <p className="mt-2">
                        All inquiries receive a personal response within{" "}
                        <strong>7 business days.</strong>
                    </p>
                </li>

                {/* 5 */}
                <li>
                    <span className="text-xl font-semibold text-blue-500 mb-2">
                        Course Update Policy
                    </span>
                    <p>
                        In accordance with NASBA Standard No. 4, all CPA
                        Workshop courses are developed and reviewed by subject
                        matter experts. Our update procedures include:
                    </p>
                    <ul className="list-disc pl-6 mt-2 space-y-1">
                        <li>
                            Ensuring all materials reflect the most current{" "}
                            <strong>laws, regulations, and guidance.</strong>
                        </li>
                        <li>
                            Including the{" "}
                            <strong>
                                most recent publication, revision, or review
                                date
                            </strong>{" "}
                            on all course content.
                        </li>
                        <li>
                            Courses covering rapidly evolving subjects are
                            reviewed at least <strong> annually.</strong>
                        </li>
                        <li>
                            All other courses undergo formal review and revision
                            at least once every <strong>two years.</strong>
                        </li>
                    </ul>
                </li>
            </ol>

            <footer className="mt-12 pt-6 border-t text-sm text-gray-600">
                <p>For questions regarding these terms, please contact us:</p>
                <p className="mt-1">
                    📧{" "}
                    <a
                        href="mailto:support@cpaworkshop.com"
                        className="text-blue-600 underline"
                    >
                        support@cpaworkshop.com
                    </a>{" "}
                    | 📞 +1 8956238956
                </p>
            </footer>
        </div>
    );
}
